# Generated by Django 4.2.3 on 2023-08-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_comment_user_alter_follower_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='comment',
        ),
        migrations.AlterField(
            model_name='follower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(upload_to='image_posts/'),
        ),
    ]
