# Generated by Django 4.2.3 on 2023-08-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_imagepost_comment_alter_follower_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='comment_counts',
            field=models.IntegerField(default=0),
        ),
    ]
