# Generated by Django 4.2.3 on 2023-08-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_imagepost_comment_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='comment_counts',
        ),
    ]
