# Generated by Django 4.2.3 on 2023-08-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_remove_imagepost_comment_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
