# Generated by Django 4.2.3 on 2023-09-19 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Follower_Model',
        ),
    ]
